Update event types in bridges using Slack and Zendesk targets
triggermesh/bridges pull request #75
Opened 2020-10-05 12:37 UTC by antoineco

As a bonus:
* Remove Cron-Zendesk bridge, which doesn't work without transformation and is not the best example of Zendesk bridge anyway (we have a few better ones in the repo).
* Release the images used in the Oracle demo bridge to `triggermesh/bridge-examples`. They were apparently not released at all until now.
* Use a Python 3 base image in Oracle Source translators. 
* Return 400 instead of 204 in case of bad request in Oracle Source translators.
* Remove duplicate Content-Type header in Oracle Source translators.

2020-10-05 12:41 UTC, antoineco reviewed
Notes

2020-10-05 12:41 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
>      )
I'm not sure why we even respond with an event here, as opposed to just responding `status: 400`, since the event doesn't even have a body. @cab105 do you know?

2020-10-05 12:41 UTC, antoineco commented on bridges/oracle-source/translators/trans-zendesk.py
>      )
Same here.

2020-10-05 22:11 UTC, cab105 commented on bridges/oracle-source/translators/trans-slack.py
>      )
This goes towards an earlier question on how we handle and report failure scenarios. In the error scenarios for this translator, the incoming event is not relevant, but maybe handled by another sink, hence the empty body and the no content status vs failing outright.

2020-10-06 00:34 UTC, JeffNeff reviewed
I started to make suggestions on all of the event types & sources but there are too many, it would break the bridge, and it's past the scope of this PR.. I am guilty of this as well, but post our discussion on the github-bumblebee-twilio bridge I really do not like to see arbitrary events created anymore and am a big proponent of transformation services returning a CE-Type of the event it's being used to transform. 

The use of CeSource here is also a bit odd. but I think that's just because I don't have a full understanding of how the Oracle Source functions yet.

2020-10-06 00:34 UTC, JeffNeff commented on bridges/oracle-source/translators/trans-zendesk.py
> +    headers['Ce-Type']='io.triggermesh.targets.sink'
```suggestion
    headers['Ce-Type']='io.triggermesh.oracle.db.event'
```

2020-10-06 00:34 UTC, JeffNeff commented on bridges/zendesk-sendgrid/zendesk-sendgrid.yaml
> +              type: io.triggermesh.sendgrid.email.send
nice

2020-10-06 00:36 UTC, JeffNeff approved these changes
I am approving because I think that my concerns and comments are nits and can be considered past the scope of this PR.

2020-10-06 10:06 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
>      )
@cab105 just to make sure I understand correctly: we _want_ to return ACK even if we can't accept the event, so I should revert that change. Correct?

2020-10-06 10:09 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
> +    headers['Ce-Type']='io.triggermesh.targets.sink'
About the _source_ type: fully agree.

About the header: you're mixing _source_ and _destination_ events here. The payload generated by the source is semantically different from the payload accepted by the target. Different schema == different type.

2020-10-06 10:25 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
> +        headers['Ce-Type']='com.slack.webapi.chat.postMessage'
At that point all targets addressed in that PR are already conformant. This PR is "fixing" the examples so they work with our latest target versions.

2020-10-06 10:25 UTC, antoineco commented on bridges/oracle-source/translators/trans-zendesk.py
> +    headers['Ce-Type']='io.triggermesh.targets.sink'
See comment above. This is not  an Oracle event.

2020-10-06 16:36 UTC, cab105 requested changes
Thank you for the much needed cleanup. Did leave a few comments, and a nit or two.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/Dockerfile
> +FROM python:3.8-slim
I hope this has been tested as, last I checked, the version of flask being pulled in is not python 3.x compatible.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/Makefile
> +clean: $(imgclean) ;
The semicolons are not necessary here

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/Makefile
> +	@docker image build --build-arg TARGET=$* -t $($@_img_name) ./
Note that `@` means the command will not be echoed to the terminal, and would prefer seeing the docker command in this case.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-slack.py
> +    headers['Ce-Type']='io.triggermesh.targets.sink'
Given `sink()` is used for error scenarios, this should reflect that the event came from the translator, and _not_ the Oracle DB source as that has it's own event. If the current name is not clear, than do change it.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-slack.py
>      )
This goes towards my understanding of a few months ago where I was not sure if processing stops upon a non-OK status code. Also, did not realize an empty object would send `{}` vs. `` as json.dumps(body) will result in the script crashing on `nil`

Granted this particular file is my very lazy coding.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-slack.py
> +        headers['Ce-Type']='com.slack.webapi.chat.postMessage'
I'll admit this has not been kept up to date given the relabeling/renaming/refactoring of our targets. If we're happy with the current state of the targets, then this should be the only thing being touched.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-slack.py
> +                status=201,
We're POSTing data to be processed by the target, and not creating, right?

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-zendesk.py
> -    headers['Content-Type']='application/json'
Still need to specify a Content-Type of `application/json` as per the http spec.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-zendesk.py
> +    # Handle the new order event by sending it to an Oracle cloud function
Oracle Cloud should be done here if it will be capitalized.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/oracle-bridge-slack-demo.yaml
> +              - image: gcr.io/triggermesh/bridge-examples/oracle-slack:latest
Does `bridge-examples` exist in gcr now?

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-slack.py
> -    headers['Content-Type']='application/json'
Still need to specify a Content-Type of `application/json` as per the http spec.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-slack.py
> -    headers['Content-Type']='application/json'
Still need to specify a Content-Type of `application/json` as per the http spec.

2020-10-06 16:36 UTC, cab105 commented on bridges/oracle-source/translators/trans-zendesk.py
> -    headers['Content-Type']='application/json'
Still need to specify a Content-Type of `application/json` as per the http spec.

2020-10-06 17:32 UTC, antoineco commented on bridges/oracle-source/translators/Dockerfile
> +FROM python:3.8-slim
I did it because the shebang in those scripts indicates `python3`, maybe it's wrong, I need to check.

2020-10-06 17:32 UTC, antoineco commented on bridges/oracle-source/translators/Makefile
> +clean: $(imgclean) ;
Will remove

2020-10-06 17:32 UTC, antoineco commented on bridges/oracle-source/translators/Makefile
> +	@docker image build --build-arg TARGET=$* -t $($@_img_name) ./
Will do

2020-10-06 17:34 UTC, antoineco commented on bridges/oracle-source/translators/trans-zendesk.py
> -    headers['Content-Type']='application/json'
What about the `mimetype=application/json` right below? One of them must go.

2020-10-06 17:37 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
> +    headers['Ce-Type']='io.triggermesh.targets.sink'
At this stage I don't think it matters, let's wait until the aforementioned story is clarified.

2020-10-06 17:39 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
>      )
OK I don't feel like bikeshedding this so I'll revert to `204` and remove the body completely.

2020-10-06 17:43 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
> +                status=201,
I though [`201`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201) was a good way to indicate that the transformation led to the creation of a new event, as opposed to just ingesting some information and storing it.

I'll revert, don't feel like bikeshedding this.

2020-10-06 17:49 UTC, antoineco commented on bridges/oracle-source/oracle-bridge-slack-demo.yaml
> +              - image: gcr.io/triggermesh/bridge-examples/oracle-slack:latest
Yup

2020-10-06 17:49 UTC, antoineco commented on bridges/oracle-source/translators/trans-zendesk.py
> +    # Handle the new order event by sending it to an Oracle cloud function
Nice  catch!

2020-10-06 17:52 UTC, antoineco commented on bridges/oracle-source/translators/Makefile
> +	@docker image build --build-arg TARGET=$* -t $($@_img_name) ./
[Done](https://github.com/triggermesh/bridges/compare/9432d455f36614dc3e2aa12a12893938591a3819..a1e9237d9bdde6a82eda452422ef565a309664a3)

2020-10-06 17:53 UTC, antoineco commented on bridges/oracle-source/translators/Makefile
> +clean: $(imgclean) ;
[Done](https://github.com/triggermesh/bridges/compare/9432d455f36614dc3e2aa12a12893938591a3819..a1e9237d9bdde6a82eda452422ef565a309664a3)

2020-10-06 17:55 UTC, antoineco commented on bridges/oracle-source/translators/trans-zendesk.py
> +    # Handle the new order event by sending it to an Oracle cloud function
[Done](https://github.com/triggermesh/bridges/compare/a1e9237d9bdde6a82eda452422ef565a309664a3..e21f9aded7a542d28391eacf92860a3b25e4d62e)

2020-10-06 17:57 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
> +                status=201,
[Done](https://github.com/triggermesh/bridges/compare/e21f9aded7a542d28391eacf92860a3b25e4d62e..51bc7f534c57e4acaf1cca96bf9b82811740a19d)

2020-10-06 17:58 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
> -    headers['Content-Type']='application/json'
See previous comment, `mimetype=application/json` is already set below.

2020-10-06 17:58 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
> -    headers['Content-Type']='application/json'
See previous comment, `mimetype=application/json` is already set below.

2020-10-06 17:58 UTC, antoineco commented on bridges/oracle-source/translators/trans-zendesk.py
> -    headers['Content-Type']='application/json'
See previous comment, `mimetype=application/json` is already set below.

2020-10-06 18:02 UTC, antoineco commented on bridges/oracle-source/translators/trans-slack.py
>      )
[Done](https://github.com/triggermesh/bridges/compare/51bc7f534c57e4acaf1cca96bf9b82811740a19d..e5acec33ba569a071b9966db745bf385978a4132)

2020-10-06 18:06 UTC, antoineco commented on bridges/oracle-source/translators/Dockerfile
> +FROM python:3.8-slim
[Reverted](https://github.com/triggermesh/bridges/compare/e5acec33ba569a071b9966db745bf385978a4132..82a463b59c428e4b6dfcd0c96e0a94a66580d867)

2020-10-06 18:18 UTC, antoineco commented
@cab105 I think all your comments were addressed, this should be ready for another review.

2020-10-06 21:15 UTC, cab105 commented on bridges/oracle-source/translators/trans-slack.py
> +    headers['Ce-Type']='io.triggermesh.targets.sink'
Understood.

2020-10-06 21:16 UTC, cab105 commented on bridges/oracle-source/translators/trans-zendesk.py
> -    headers['Content-Type']='application/json'
Okay okay. You can kill it.

2020-10-07 07:57 UTC, merged