Creates OCI Metrics -> DataDog bridge
triggermesh/bridges pull request #78
Opened 2020-10-12 16:02 UTC by JeffNeff

2020-10-14 22:43 UTC, cab105 commented on oci-datadog/oci-datadog.yaml
> +    - object:
As a heads up, this should reflect the sample definition from: https://github.com/triggermesh/event-sources/blob/oracle-metrics/config/samples/ocimetricssource.yaml

2020-10-15 14:08 UTC, antoineco requested changes

2020-10-15 14:08 UTC, antoineco commented on bridges/oci-datadog/oci-datadog.yaml
> +                    - image: gcr.io/neffdev/oci-trans:latest
Heads up: before merging we should have this released at gcr.io/triggermesh/bridge-examples/ (and maybe use a name that's more explicit than just "trans", such as `oci-datadog-transformation`.

2020-10-15 14:08 UTC, antoineco commented on bridges/oci-datadog/oci-datadog.yaml
> +            template:
Those are a lot of spaces. Let's re-verify the file, and maybe auto-format it.

2020-10-15 14:08 UTC, antoineco commented on bridges/oci-datadog/oci-datadog.yaml
> +          agent: "10.1.67.54"
Should be an internal K8S name, or an empty string.

2020-10-15 14:08 UTC, antoineco commented on bridges/oci-datadog/oci-datadog.yaml
> +          broker: oci-datadog
We should be using anchors to avoid repeating the names of the broker and target everywhere, like in https://github.com/triggermesh/bridges/blob/master/bridges/zendesk-zendesk/zendesk-zendesk-comprehend.yaml.

2020-10-15 14:08 UTC, antoineco commented on bridges/oci-datadog/translator/ksvc.yaml
> +            - image: gcr.io/triggermesh/transdatadog:latest
Should be in the bridge, like in https://github.com/triggermesh/bridges/blob/master/bridges/zendesk-zendesk/zendesk-zendesk-comprehend.yaml

2020-10-15 14:08 UTC, antoineco commented on bridges/oci-datadog/translator/trans.py
> +#!/usr/bin/env python3
@cab105 pointed out flask doesn't work with Python3

2020-10-15 14:08 UTC, antoineco commented
Just sharing some early feedback although the PR is not ready.

2020-10-16 22:16 UTC, cab105 commented on bridges/oci-datadog/translator/trans.py
> +#!/usr/bin/env python3
On the plus side, it appears that it has been fixed upstream, and confirmed it does work.

2020-10-29 22:02 UTC, antoineco commented on bridges/oci-datadog/translator/trans.py
> +            response=json.dumps(body),
There is no `body` variable defined, neither in this block nor at the global scope, won't `json.dumps` freak out?

Even if it doesn't, it would be clearer to just omit the `body` parameter.

2020-10-29 22:08 UTC, antoineco commented on bridges/oci-datadog/translator/trans.py
> +    if ce is not None:
Why would `ce` be None? If `request.get_json(force=True)` fails your code would have error'd already. Better handle a possible failure with a `try/catch`.

2020-10-29 22:08 UTC, antoineco commented on bridges/oci-datadog/translator/trans.py
> +    headers['Ce-Source']=request.headers['Ce-Source'] + "/translated"
You set all those headers, but then check if `ce` is None. The order should be reversed, no need to initialize headers if your code already failed.

2020-10-29 22:08 UTC, antoineco commented on bridges/oci-datadog/translator/trans.py
> +        print("Unkown event, skipping...")
Like I said earlier, I don't think that `else` can possibly be hit.

2020-10-29 22:08 UTC, antoineco commented on bridges/oci-datadog/translator/trans.py
> +            status=500,
You say "skip" in the log above, but then return an error code indicating a server failure (500). `400` would be more appropriate.

2020-10-30 15:43 UTC, antoineco commented on bridges/oci-datadog/translator/Dockerfile
> +COPY trans.py /trans.py
It's also much easier to monitor a process with a unique name. When all containers run the same "trans.py", good luck telling what process runs which transformation.

2020-10-30 15:44 UTC, antoineco commented on bridges/oci-datadog/translator/Dockerfile
> +COPY trans.py /trans.py
It's also much easier to monitor a process with a unique name. When all containers run the same "trans.py", good luck telling what process runs which transformation.

2020-10-30 16:37 UTC, cab105 commented on bridges/oci-datadog/translator/trans.py
> +        print("Unkown event, skipping...")
Will refactor to fix this.

2020-10-30 16:37 UTC, cab105 commented on bridges/oci-datadog/translator/trans.py
> +            response=json.dumps(body),
Good point. Although in this case `json.dumps` would return `{}`

2020-10-30 16:37 UTC, cab105 commented on bridges/oci-datadog/translator/trans.py
> +    headers['Ce-Source']=request.headers['Ce-Source'] + "/translated"
The intent was to generate an event regardless of success/failure. However, it appears the code would never reach that point.

2020-11-02 18:12 UTC, JeffNeff commented
I have re-built the docker image for the transformation post @cab105 's updates

2020-11-02 18:13 UTC, cab105 commented
> I have re-built the docker image for the transformation post @cab105 's updates

I did that with my push on Friday so it wasn't necessary, but thanks!

2020-11-02 18:23 UTC, cab105 commented on bridges/oci-datadog/200-oci-datadog.yaml
> +          oracleUser: ocid1.user.oc1..aaaaaaaaqloc
Should probably add comments to remind the user to change these values.

2020-11-02 18:23 UTC, cab105 commented on bridges/oci-datadog/200-oci-datadog.yaml
> +          oracleUser: ocid1.user.oc1..aaaaaaaaqloc
Similar with these values as they are instance specific.

2020-11-02 18:24 UTC, cab105 approved these changes

2020-11-02 18:30 UTC, merged